# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0c11f5019bcf831a1c54606f00eb144afb573e99e4a08a58ddd02eb04421b7cc901be1fc94d5070825523a260305080f01c96f3d505a278375e57a74621652d

test:
  secret_key_base: 4cedfaedbb2872d345d52e1a5dbd293c720861eee46dce064a91fb4c28aa8a69f68cad5555ab1f6299168402a7ace68dabcc3ae01d345abbca34bb1ecb2d05cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
